from wrappers.robo_wrapper import robo_make

if __name__ == "__main__":

    config = {
        "setting": {
            "camera": {
                "position": {"original": 0.0, "easy": 0.12, "hard": 0.16},
                "rotation": {"original": 0.0, "easy": 0.12, "hard": 0.16},
                "fov": {"original": 0.0, "easy": 10, "hard": 20},
            }
        },
        "channel_first": True,
        "image_height": 84,
        "image_width": 84,
        "task_def": {
            "env_name": "Door",
            "robots": "Panda",
            "controller_configs": "OSC_POSE",
            "camera_names": "agentview",
            "camera_heights": 84,
            "camera_widths": 84,
            "camera_depths": False,
            "reward_shaping": True,
            "has_renderer": False,
            "ignore_done": False,
            "control_freq": 20,
            "hard_reset": False,
            "horizon": 500,
        },
        "obs_modality": ["rgb"],
        "mode": "train",
        "scene_id": 0,
        "seed": 6,
        "moving_light": False,
        "video_background": False,
        "except_robot": True,
        "color": {
            "geom_names": None,
            "randomize_local": True,
            "randomize_material": False,
            "local_rgb_interpolation": 0.2,
            "local_material_interpolation": 0.3,
            "texture_variations": ["rgb", "checker", "noise", "gradient"],
            "randomize_skybox": True,
        },
        "_camera_": {"position": "original", "rotation": "original", "fov": "original"},
        "camera": {
            "camera_names": None,
            "randomize_position": True,
            "randomize_rotation": True,
            "randomize_fovy": True,
            "position_perturbation_size": 0.0,
            "rotation_perturbation_size": 0.0,
            "fovy_perturbation_size": 0.0,
        },
        "light": {
            "light_names": None,
            "randomize_position": False,
            "randomize_direction": False,
            "randomize_specular": False,
            "randomize_ambient": False,
            "randomize_diffuse": False,
            "randomize_active": False,
            "position_perturbation_size": 100,
            "direction_perturbation_size": 50,
            "specular_perturbation_size": 0.3,
            "ambient_perturbation_size": 0.3,
            "diffuse_perturbation_size": 0.3,
        },
        "dynamic": {
            "randomize_density": False,
            "randomize_viscosity": False,
            "density_perturbation_ratio": 0.1,
            "viscosity_perturbation_ratio": 0.1,
            "body_names": None,
            "randomize_position": False,
            "randomize_quaternion": False,
            "randomize_inertia": False,
            "randomize_mass": False,
            "position_perturbation_size": 0.0015,
            "quaternion_perturbation_size": 0.003,
            "inertia_perturbation_ratio": 0.02,
            "mass_perturbation_ratio": 0.02,
            "geom_names": None,
            "randomize_friction": False,
            "randomize_solref": False,
            "randomize_solimp": False,
            "friction_perturbation_ratio": 0.1,
            "solref_perturbation_ratio": 0.1,
            "solimp_perturbation_ratio": 0.1,
            "joint_names": None,
            "randomize_stiffness": False,
            "randomize_frictionloss": False,
            "randomize_damping": False,
            "randomize_armature": False,
            "stiffness_perturbation_ratio": 0.1,
            "frictionloss_perturbation_size": 0.05,
            "damping_perturbation_size": 0.01,
            "armature_perturbation_size": 0.01,
        },
    }

    action_repeat = 2  # Feel free to change this

    env = robo_make(config, action_repeat=action_repeat)
